# Generated by Django 3.0.14 on 2023-05-17 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0003_meeting_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
