# Generated by Django 3.0.14 on 2023-05-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20230517_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
